apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boutique-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: boutique-ip
    networking.gke.io/managed-certificates: boutique-cert
spec:
  rules:
  - host: 34-54-178-42.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: ai-agent
            port:
              number: 80
