apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-agent
  labels:
    app: ai-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-agent
  template:
    metadata:
      labels:
        app: ai-agent
    spec:
      containers:
      - name: ai-agent
        image: us-central1-docker.pkg.dev/plucky-dryad-472321-g1/ai-agents/ai-agent:v2
        ports:
        - containerPort: 8080
        env:
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: gemini-api-key
              key: key
        - name: CATALOG_URL
          value: "http://productcatalogservice:3550"
        - name: CART_URL
          value: "http://cartservice:7070"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-agent
spec:
  selector:
    app: ai-agent
  ports:
  - name: http
    port: 80
    targetPort: 8080
